-- Alex Board automatic capacity cleanup v1
-- Keeps reusable board-table space out of the capacity-pressure calculation and,
-- when pressure reaches 470 MiB, deletes the least-recently-used boards until
-- approximately 200 MiB of logical board data has been selected.

begin;

create extension if not exists pgstattuple with schema extensions;

create table if not exists public.board_cleanup_log (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  raw_database_bytes_before bigint,
  raw_database_bytes_after bigint,
  capacity_pressure_bytes_before bigint,
  capacity_pressure_bytes_after bigint,
  estimated_garbage_bytes bigint not null default 0,
  estimated_board_bytes bigint not null default 0,
  boards_deleted integer not null default 0,
  deleted_board_ids text[] not null default '{}',
  storage_objects_deleted integer not null default 0,
  storage_bytes_deleted bigint not null default 0,
  storage_error text,
  error_text text,
  check (status in (
    'running',
    'skipped_below_threshold',
    'garbage_only',
    'boards_deleted',
    'dry_run',
    'failed',
    'busy',
    'unresolved_pressure'
  ))
);

revoke all on public.board_cleanup_log from public, anon, authenticated;
grant select, insert, update, delete on public.board_cleanup_log to service_role;
grant usage, select on sequence public.board_cleanup_log_id_seq to service_role;

create or replace function public.board_cleanup_capacity_pressure_v1()
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_raw bigint := pg_database_size(current_database());
  v_reusable bigint := 0;
  v_table_reusable bigint := 0;
  v_table text;
  v_tables text[] := array[
    'public.boards',
    'public.board_actions',
    'public.board_objects',
    'public.board_snapshots',
    'public.board_tombstones',
    'public.board_import_chunks',
    'public.board_actions_v8',
    'public.board_action_heads_v8',
    'public.board_import_chunks_v8',
    'public.board_object_states_v8',
    'public.board_object_state_heads_v8',
    'public.board_object_locks_v8',
    'public.board_action_noop_outcomes_v8'
  ];
begin
  foreach v_table in array v_tables loop
    if to_regclass(v_table) is null then
      continue;
    end if;
    begin
      execute format(
        'select coalesce(dead_tuple_len, 0)::bigint + coalesce(approx_free_space, 0)::bigint from extensions.pgstattuple_approx(%L::regclass)',
        v_table
      ) into v_table_reusable;
      v_reusable := v_reusable + greatest(0, coalesce(v_table_reusable, 0));
    exception when others then
      -- Capacity checks must remain available even if one relation cannot be sampled.
      v_table_reusable := 0;
    end;
  end loop;

  return jsonb_build_object(
    'rawDatabaseBytes', v_raw,
    'reusableBytes', least(v_raw, greatest(0, v_reusable)),
    'pressureBytes', greatest(0, v_raw - least(v_raw, greatest(0, v_reusable)))
  );
end
$$;

revoke all on function public.board_cleanup_capacity_pressure_v1()
  from public, anon, authenticated;
grant execute on function public.board_cleanup_capacity_pressure_v1() to service_role;

create or replace function public.board_cleanup_board_bytes_v1(p_board_id text)
returns bigint
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_total bigint := 0;
begin
  select v_total + coalesce(sum(pg_column_size(b)), 0)::bigint into v_total
  from public.boards b where b.id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_actions t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_objects t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_snapshots t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_tombstones t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_import_chunks t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_actions_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_action_heads_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_import_chunks_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_object_states_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_object_state_heads_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_object_locks_v8 t where t.board_id = p_board_id;
  select v_total + coalesce(sum(pg_column_size(t)), 0)::bigint into v_total
  from public.board_action_noop_outcomes_v8 t where t.board_id = p_board_id;
  return greatest(1, coalesce(v_total, 0));
end
$$;

revoke all on function public.board_cleanup_board_bytes_v1(text)
  from public, anon, authenticated;
grant execute on function public.board_cleanup_board_bytes_v1(text) to service_role;

create or replace function public.run_board_capacity_cleanup_v1(
  p_cleanup_token text,
  p_capacity_override bigint default null,
  p_target_bytes bigint default 209715200,
  p_dry_run boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, extensions, pg_temp
as $$
declare
  c_threshold_bytes constant bigint := 492830720;
  c_default_target_bytes constant bigint := 209715200;
  v_run_id bigint;
  v_before jsonb;
  v_after jsonb;
  v_decision_pressure bigint;
  v_deleted_ids text[] := '{}';
  v_estimated_board_bytes bigint := 0;
  v_estimated_garbage_bytes bigint := 0;
  v_boards_deleted integer := 0;
  v_status text;
  v_target bigint := greatest(1, coalesce(p_target_bytes, c_default_target_bytes));
begin
  if nullif(p_cleanup_token, '') is null or not exists (
    select 1
    from vault.decrypted_secrets s
    where s.name = 'board_cleanup_token'
      and s.decrypted_secret = p_cleanup_token
  ) then
    raise exception 'Invalid cleanup token' using errcode = '42501';
  end if;

  if not pg_try_advisory_xact_lock(hashtext('alex-board-capacity-cleanup-v1')) then
    insert into public.board_cleanup_log(status, finished_at)
    values ('busy', now()) returning id into v_run_id;
    return jsonb_build_object('runId', v_run_id, 'status', 'busy');
  end if;

  v_before := public.board_cleanup_capacity_pressure_v1();

  if not p_dry_run then
    select
      coalesce((select sum(pg_column_size(t)) from public.board_object_locks_v8 t where t.expires_at <= now()), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_import_chunks_v8 t where t.created_at < now() - interval '24 hours'), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_import_chunks t where t.created_at < now() - interval '24 hours'), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_action_noop_outcomes_v8 t where t.created_at < now() - interval '30 days'), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_actions t), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_objects t), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_snapshots t), 0)
      + coalesce((select sum(pg_column_size(t)) from public.board_tombstones t), 0)
    into v_estimated_garbage_bytes;

    delete from public.board_object_locks_v8 where expires_at <= now();
    delete from public.board_import_chunks_v8 where created_at < now() - interval '24 hours';
    delete from public.board_import_chunks where created_at < now() - interval '24 hours';
    delete from public.board_action_noop_outcomes_v8 where created_at < now() - interval '30 days';
    delete from public.board_cleanup_log where started_at < now() - interval '90 days';

    -- Task 1 removes the last supported runtime dependency on these protocol-v7 tables.
    -- Old RPC execution is revoked, so any rows here are legacy duplication/history data.
    delete from public.board_actions;
    delete from public.board_objects;
    delete from public.board_snapshots;
    delete from public.board_tombstones;
    delete from public.board_import_chunks;
  end if;

  v_after := public.board_cleanup_capacity_pressure_v1();
  v_decision_pressure := coalesce(
    p_capacity_override,
    (v_after->>'pressureBytes')::bigint,
    (v_before->>'pressureBytes')::bigint,
    0
  );

  insert into public.board_cleanup_log(
    status,
    raw_database_bytes_before,
    capacity_pressure_bytes_before,
    estimated_garbage_bytes
  ) values (
    'running',
    (v_before->>'rawDatabaseBytes')::bigint,
    (v_before->>'pressureBytes')::bigint,
    v_estimated_garbage_bytes
  ) returning id into v_run_id;

  if v_decision_pressure < c_threshold_bytes then
    v_status := case
      when not p_dry_run and v_estimated_garbage_bytes > 0 then 'garbage_only'
      else 'skipped_below_threshold'
    end;
    update public.board_cleanup_log
    set status = v_status,
        finished_at = now(),
        raw_database_bytes_after = (v_after->>'rawDatabaseBytes')::bigint,
        capacity_pressure_bytes_after = (v_after->>'pressureBytes')::bigint
    where id = v_run_id;

    return jsonb_build_object(
      'runId', v_run_id,
      'status', v_status,
      'dryRun', p_dry_run,
      'deletedBoardIds', '[]'::jsonb,
      'estimatedGarbageBytes', v_estimated_garbage_bytes,
      'rawDatabaseBytesBefore', (v_before->>'rawDatabaseBytes')::bigint,
      'capacityPressureBytesBefore', (v_before->>'pressureBytes')::bigint,
      'rawDatabaseBytesAfter', (v_after->>'rawDatabaseBytes')::bigint,
      'capacityPressureBytesAfter', (v_after->>'pressureBytes')::bigint
    );
  end if;

  with sized as (
    select
      b.id,
      coalesce(b.last_lesson_at, b.updated_at, b.created_at) as age_key,
      public.board_cleanup_board_bytes_v1(b.id) as board_bytes
    from public.boards b
  ), ordered as (
    select
      id,
      age_key,
      board_bytes,
      sum(board_bytes) over (order by age_key, id) as cumulative_bytes
    from sized
  ), selected as (
    select *
    from ordered
    where cumulative_bytes - board_bytes < v_target
  )
  select
    coalesce(array_agg(id order by age_key, id), '{}'),
    coalesce(sum(board_bytes), 0)::bigint
  into v_deleted_ids, v_estimated_board_bytes
  from selected;

  if coalesce(array_length(v_deleted_ids, 1), 0) = 0 then
    v_status := 'unresolved_pressure';
  elsif p_dry_run then
    v_status := 'dry_run';
  else
    delete from public.boards where id = any(v_deleted_ids);
    get diagnostics v_boards_deleted = row_count;
    v_status := 'boards_deleted';
  end if;

  v_after := public.board_cleanup_capacity_pressure_v1();

  update public.board_cleanup_log
  set status = v_status,
      finished_at = now(),
      raw_database_bytes_after = (v_after->>'rawDatabaseBytes')::bigint,
      capacity_pressure_bytes_after = (v_after->>'pressureBytes')::bigint,
      estimated_board_bytes = v_estimated_board_bytes,
      boards_deleted = v_boards_deleted,
      deleted_board_ids = case when p_dry_run then '{}'::text[] else v_deleted_ids end
  where id = v_run_id;

  return jsonb_build_object(
    'runId', v_run_id,
    'status', v_status,
    'dryRun', p_dry_run,
    'deletedBoardIds', case when p_dry_run then '[]'::jsonb else to_jsonb(v_deleted_ids) end,
    'selectedBoardIds', to_jsonb(v_deleted_ids),
    'estimatedGarbageBytes', v_estimated_garbage_bytes,
    'estimatedBoardBytes', v_estimated_board_bytes,
    'boardsDeleted', v_boards_deleted,
    'rawDatabaseBytesBefore', (v_before->>'rawDatabaseBytes')::bigint,
    'capacityPressureBytesBefore', (v_before->>'pressureBytes')::bigint,
    'rawDatabaseBytesAfter', (v_after->>'rawDatabaseBytes')::bigint,
    'capacityPressureBytesAfter', (v_after->>'pressureBytes')::bigint
  );
end
$$;

revoke all on function public.run_board_capacity_cleanup_v1(text, bigint, bigint, boolean)
  from public, anon, authenticated;
grant execute on function public.run_board_capacity_cleanup_v1(text, bigint, bigint, boolean)
  to service_role;

create or replace function public.finish_board_capacity_cleanup_v1(
  p_run_id bigint,
  p_storage_objects integer,
  p_storage_bytes bigint,
  p_storage_error text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.board_cleanup_log
  set storage_objects_deleted = greatest(0, coalesce(p_storage_objects, 0)),
      storage_bytes_deleted = greatest(0, coalesce(p_storage_bytes, 0)),
      storage_error = nullif(p_storage_error, ''),
      status = case
        when nullif(p_storage_error, '') is not null then 'failed'
        else status
      end,
      finished_at = coalesce(finished_at, now())
  where id = p_run_id;
end
$$;

revoke all on function public.finish_board_capacity_cleanup_v1(bigint, integer, bigint, text)
  from public, anon, authenticated;
grant execute on function public.finish_board_capacity_cleanup_v1(bigint, integer, bigint, text)
  to service_role;

commit;
