import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles.css';
import './eraser-object-only.css';
import './floating-drawing-controls.css';
import './floating-drawing-controls-language-fix.css';
import './three-dot-drawing-controls.css';
import './ipad-system-color-palette.css';
import './ipad-system-color-palette-scale.css';
import './historyKeyboardShortcuts.js';
import './pencilFreezeDiagnostics.js';
import './dock-layout-controller.js';
import './floating-drawing-controls-enhancer.js';
import './ipad-system-color-palette.js';
import './dock-style-accessories.css';
import './dock-style-accessories.js';
import './dock-layout-runtime.js';
import './dock-history-icons.css';
import './dock-history-icons.js';
import './dock-style-presets-gear.js';
import './floating-toolbar-layout.css';
import './mobile-premium-glass-fallback.css';
import './refractive-glass-lensing.css';
import './refractive-glass-lensing.js';
import './refractive-glass-desktop-surface.js';
import './board-settings-gear.css';
import './bring-here-option-3.css';
import './board-settings-gear.js';
import './board-fullscreen.css';
import './dock-layout-modes.css';
import './board-fullscreen.js';

createRoot(document.getElementById('root')).render(<App />);